lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :cookie_auth do
    plug TaskTrackerWeb.Authentication
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :put_secure_browser_headers
  end

  scope "/api", TaskTrackerWeb do
    pipe_through :api
    pipe_through :cookie_auth
    resources "/tasks/:task_id/time_blocks", TimeBlockController
  end

  scope "/admin", TaskTrackerWeb do
    pipe_through :browser
    pipe_through :cookie_auth
    resources "/users", UserController
    resources "/", UserController
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser
    get "/register", UserController, :new_self
    post "/register", UserController, :create_self
    # all authenticated routes below
    get "/signin", AuthController, :new
    post "/signin", AuthController, :create
    pipe_through :cookie_auth
    get "/signout", AuthController, :delete
    get "/account/:id", UserController, :show_self
    get "/account/:id/edit", UserController, :edit_self
    post "/account/:id/edit", UserController, :update_self
    resources "/tasks", TaskController
    get "/*path", RedirectController, :index
  end


end

lib/task_tracker_web/views/layout_view.ex
defmodule TaskTrackerWeb.LayoutView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello TaskTracker!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= if get_flash(@conn, :error) do  %>
        <div class="alert alert-danger" role="alert">
          <%= get_flash(@conn, :error) %>
        </div>
    <% end %>
    <div class="container">
	  <br>
	  <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="<%= task_path(@conn, :index) %>">TaskTracker</a>
            <ul class="navbar-nav mr-auto">
            <%= if Map.get(Plug.Conn.get_session(@conn, "user") || %{}, :is_admin, false) do %>
                <li class="nav-item">
                <a class="nav-link" href="<%= user_path(@conn, :index) %>">Admin</a>
                </li>
            <% end %>
            </ul>
            <ul class="navbar-nav ml-auto">
            <%= if !!Plug.Conn.get_session(@conn, "user") do %>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= Map.get(Plug.Conn.get_session(@conn, "user"), :first_name) %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="nav-link" href="<%= user_path(@conn, :show_self, Plug.Conn.get_session(@conn, "user")) %>">Account</a>
                    <a class="nav-link" href="<%= auth_path(@conn, :delete) %>">Sign out</a>
                </div>
                </li>
            <% else %>
                 <li class="nav-item">
                    <a class="nav-link" href="<%= auth_path(@conn, :new) %>">Sign in</a>
                </li>
            <% end %>
            </ul>

      </nav>
      <br><br>
      <main role="main">
        <div class="container">
        <%= render @view_module, @view_template, assigns %>
        </div>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>